{
  "hash": "2e659998c80908b318f2cb17f34c0b71",
  "result": {
    "engine": "knitr",
    "markdown": "---\n# TITLE & AUTHOR\ntitle: \"(1) Introduction to Causal Inference\"\nsubtitle: \"Causal Data Science for Business Analytics\"\nauthor: \"Christoph Ihl\"\ninstitute: \"Hamburg University of Technology\"\ndate: today\ndate-format: \"dddd, D. MMMM YYYY\"\n# FORMAT OPTIONS\nformat: \n  revealjs:\n    width: 1600\n    height: 900\n    footer: \"Causal Data Science: (1) Introduction to Causal Inference\"\n    slide-number: true\n---\n\n\n\n# Course Overview {data-stack-name=\"Overview\"}\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n<style type=\"text/css\">\ndiv.callout-note{border-left-color:#00C1D4 !important}div.callout-note.callout-style-default .callout-title{background-color:#005e73;color:white}.callout.callout-style-default{border-left:solid #005e73 .3rem;border-right:solid 1px #005e73;border-top:solid 1px #005e73;border-bottom:solid 1px #005e73}\n</style>\n:::\n\n\n\n\n\n\n\n## Learning Goals\n\n::: {.nonincremental}\n- Understand the difference between \"correlation” and “causation\" \n- Understand the shortcomings of current correlation-based approaches\n- Develop causal knowledge relevant for specific data-driven decisions\n- Formalize intuition about causal relationships using a \"language\" of causality\n- Derive causal hypotheses that can be tested with data\n- Discuss the conceptual ideas behind state-of-the-art causal data science tools and algorithms\n- Carry out causal data analyses with state-of-the-art tools\n:::\n\n\n\n## Map of Causality\n\n![](_images/1/causality_map.png){.r-stretch fig-align=\"center\"}\n\n\n::: {.source}\nSource: [https://towardsdatascience.com](https://towardsdatascience.com/how-to-understand-the-world-of-causality-c698cdc9f27c) (2023).\n:::\n\n\n\n\n\n## Preliminary Schedule {.smaller}\n\n| Session | Date | Topic |\n| --- | --- | --- |\n| 1 | April 15 & 16 | Introduction to Causal Inference |\n| 2 | April 22 & 21 | Graphical Causal Models |\n| 3 | April 29 & 30 | Randomized Experiments |\n| 4 | May 6 & 7 | Observed Confounding |\n| 5 | May 13 & 14 | Double Machine Learning | \n| - | May 20 & 21 | Holiday |\n| 6 | May 27 & 28 | Effect Heterogeneity |\n| 7 | June 3 & 4 | Unobserved Confounding & Instrumental Variables |\n| 8 | June 10 & 11 | Difference-in-Difference |\n| 9 | June 17 & 18 | Synthetic Control |\n| 10 | June 24 & 25 | Regression Discontinuity |\n| 11 | July 1 & 2 | Causal Mediation  |\n| 12 | July 8 & 9 | Further Topics in Causal Machine Learning |\n\n\n## Course Structure\n\n- `Lecture - Causal Data Science:` Monday, 11.30 - 13.00, Building D, Room D - 1.023\n- `Lab - Business Analytics with Causal Data Science:` Tuesday, 15.00 - 16.30, Building O, Room O - 0.007\n\n<br>\n\n- `Examination:` 10 challenges related to each topic documented in a lab journal\n\n<br>\n\n- `Contact:` Oliver Mork ([oliver.mork@tuhh.de](mailto:oliver.mork@tuhh.de))\n\n\n\n## Course Literature {.smaller}\n\n::: {.panel-tabset}\n\n### **Primary:**\n\n* Ding, Peng (2023). A First Course in Causal Inference. arXiv preprint arXiv:2305.18793.\n* Facure, Matheus (2023). Causal Inference in Python - Applying Causal Inference in the Tech Industry. O'Reilly Media.\n* Huber, Martin (2023). Causal analysis: Impact evaluation and Causal Machine Learning with applications in R. MIT Press, 2023.\n* Neal, Brady (2020). Introduction to causal inference from a Machine Learning Perspective. Course Lecture Notes (draft).\n\n### **Secondary:**\n\n* Angrist, J. D., & Pischke, J. S. (2014). Mastering metrics: The path from cause to effect. Princeton university press.\n* Cunningham, Scott (2021). Causal Inference: The Mixtape, New Haven: Yale University Press.\n* Gertler, Paul J., et al. (2016). Impact evaluation in practice. World Bank Publications.\n* Hernán Miguel A., and Robins James M. (2020). Causal Inference: What If. Boca Raton: Chapman & Hall/CRC.\n* Huntington-Klein, Nick (2021). The effect: An introduction to research design and causality. Chapman and Hall/CRC.\n* Imbens, G. W., & Rubin, D. B. (2015). Causal inference in statistics, social, and biomedical sciences. Cambridge University Press.\n* Mullainathan, Sendhil, and Jann Spiess. (2017). Machine Learning: An Applied Econometric Approach. Journal of Economic Perspectives, 31(2): 87–106.\n* Pearl, Judea, and Dana Mackenzie (2018). The Book of Why. Basic Books, New York, NY.\n* Pearl, Judea, Madelyn Glymour, and Nicholas P. Jewell (2016). Causal Inference in Statistics: A Primer. John Wiley & Sons, Inc., New York, NY.\n* Peters, Jonas, Dominik Janzing, and Bernhard Schölkopf (2017). Elements of causal inference: foundations and learning algorithms. The MIT Press.\n\n:::\n\n\n\n\n\n# Course Motivation {data-stack-name=\"Motivation\"}\n\n## Causality vs. Correlation\n\n- Causality is central to human knowledge. \n- Two famous quotes from ancient Greeks:\n  - \"I would rather discover one causal law than be King of Persia.\" `(Democritus)` \n  - \"We do not have knowledge of a thing until we grasped its cause.\" `(Aristotle)`\n<br><br>\n- However:\n  - Classic statistics is about association rather than causation.\n  - Machine learning is about prediction rather than causation.\n\n\n## Causality vs. Correlation\n\n- \"Correlation does not imply causation.\"\n- \"You can not prove causality with statistics.\"\n<br><br>\n- But statistics is crucial for understanding causality:\n  - Formal language for causal inference.\n  - Methods to estimate causal effects.\n\n![](_images/1/nobel.jpeg){.r-stretch fig-align=\"center\"}\n\n\n## Causality vs. Correlation\n\n![](_images/1/hbr.png){.r-stretch fig-align=\"center\"}\n\n\n::: {.source}\nSource: [https://hbr.org/2021/11/leaders-stop-confusing-correlation-with-causation](https://hbr.org/2021/11/leaders-stop-confusing-correlation-with-causation).\n:::\n\n\n\n## Causality vs. Correlation\n\n![](_images/1/nicolas_cage.png){.r-stretch fig-align=\"center\"}\n\n\n::: {.source}\nSource: [https://www.tylervigen.com/spurious- correlations](https://www.tylervigen.com/spurious- correlations).\n:::\n\n\n## Causality vs. Correlation\n\n![](_images/1/nobel_choc.png){fig-align=\"center\" height=600}\n\n::: {.source}\nSource: Peters, Jonas. 2015. Causality: Lecture Notes, ETH Zurich.\n:::\n\n\n\n\n\n\n\n\n\n## Causality vs. Correlation\n- Correlation, or better association, is not (entirely) causation, if there is confounding association due to a common cause, i.e. a ***confounder***.\n- E.g. drinking the night before is a common cause of sleeping with shoes on and of waking up with a headache:\n\n![](_images/1/headache.png){height=400 width=\"auto\" fig-align=\"center\"}\n<br>\n\n::: {.source}\nSource: Neal, Brady (2020). Introduction to causal inference from a Machine Learning Perspective. Course Lecture Notes (draft).\n:::\n\n\n## Causality vs. Correlation\n- Correlation, or better association, is not (entirely) causation, if there is confounding association due to a common cause, i.e. a ***confounder***.\n- E.g. Consumers' purchase intent is a common cause of the amount spent on search engine marketing (SEM) (esp. for branded vs. non-branded ads) and sales (especially for frequent consumers):\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nlibrary(ggdag)\nlibrary(ggplot2)\n\ncoord_dag <- list(\n  x = c(SEM = 0, Intent = 1, Sales = 2),\n  y = c(SEM = 0, Intent = 1, Sales = 0)\n)\n\ndag <- ggdag::dagify(SEM ~ Intent,\n                     Sales ~ SEM,\n                     Sales ~ Intent,\n                     coords = coord_dag)\n\ndag %>%\n  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +\n  geom_dag_point(colour = \"grey\") +\n  geom_dag_edges() +\n  geom_dag_text(colour = \"black\", size = 5) +\n  theme_dag(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](01_intro_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n::: {.source}\n(Source: [Blake et al. (2015). Consumer heterogeneity and paid search effectiveness: A large‐scale field experiment. Econometrica, 83(1), 155-174.](http://faculty.haas.berkeley.edu/stadelis/Tadelis.pdf))\n:::\n\n\n\n# Simpson's Paradox {data-stack-name=\"Simpson's Paradox\"}\n\n## Motivating Example: Gender Pay Gap (1)\n\n| - **Reported by The New York Times in March 2019:**\n|       \"When Google conducted a study recently to determine whether \n|       the company was underpaying women and minority groups, it found \n|       that men were paid less money than women for doing similar work.\"\n\n::: {.source}\n(Source: [https://www.nytimes.com/2019/03/04/technology/google-gender-pay-gap.html](https://www.nytimes.com/2019/03/04/technology/google-gender-pay-gap.html))\n:::\n\n- The study led Google to increase the pay of its male employees to fight this blatant discrimination of men.\n- What's going on here? Wasn't Google just recently accused of discriminating against women, not men?\n\n|       \"Department of Labor claims that Google systematically underpays its\n|       female employees.\"\n\n::: {.source}\n(Source: [https://www.theverge.com/2017/4/8/15229688/department-of-labor-google-gender-pay-gap](https://www.theverge.com/2017/4/8/15229688/department-of-labor-google-gender-pay-gap))\n:::\n\n\n\n## Motivating Example: Gender Pay Gap (2)\n\n- Suppose we collected data on wages payed to 100 women and 100 men in company X. \n- We observe the following average monthly salaries for women and men in management and non-management positions (case numbers in parentheses):\n\n|  | Women | Men |\n|:------|:------:|:------:|:------:|\n| Non-management: |  $3,163.30 (87)  |    $3,015.18 (59)   |\n| Management: |  $5,592.44 (13) |   $5,319.82 (41)   |\n\n\n<br>\n\n- Our goal is to estimate the magnitude of the gender pay gap in company X. How should we tackle this problem?\n\n\n\n## Motivating Example: Gender Pay Gap (3) {.smaller}\n\n-   On average, women earn less in this example:\n$$\n   \\left(\\frac{87}{100} \\cdot \\$3163.30\\right) + \\left(\\frac{13}{100} \\cdot \\$5592.44\\right) - \n   \\left(\\frac{59}{100} \\cdot \\$3015.18\\right) + \\left(\\frac{41}{100} \\cdot \\$5319.82\\right) \\\\\n   \\approx -\\$481\n$$\n-   But in each subcategory women actually have higher salaries:\n\n|   - **Non- Management**: $\\$3163.30 - \\$3015.18 = \\$148.12$\n\n|   - **Management**:    $\\$5592.44 - \\$5319.82 = \\$272.62$\n\n-   Conditioning on job position gives the adjusted gender pay gap:\n\n$$\n   \\left(\\frac{87 + 59}{200} \\cdot \\$148.12\\right) + \\left(\\frac{13 + 41}{200} \\cdot \\$272.62\\right) \\approx \\$181.74\n$$\n\n-   Which estimate gives us a more accurate picture of the gender pay gap?\n\n\n## Motivating Example: Gender Pay Gap (4)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\ndata <- data.frame(\n  Salary = c(5319.82, 3015.18, 5592.44, 3163.30, 3960.08, 3479.09),\n  Position = c(\"Management\", \"Non-Management\", \"Management\", \"Non-Management\", \"All Positions\", \"All Positions\"),\n  Gender = c(\"Male\", \"Male\", \"Female\", \"Female\", \"Male\", \"Female\")\n)\n\nlibrary(ggplot2)\n\ndata |> \n  ggplot(aes(x=Gender, y=Salary, group=Position, colour=Position)) +\n  geom_line() + geom_point() + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](01_intro_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n## Simpson's Paradox (1)\n\n-   The phenomenon that a statistical association, which holds in a population, can be reversed in every subpopulation is named after the British statistician Edward Simpson.\n- Simpson's paradox well-known, for example, in epidemiology and labor economics.\n- In the gender pay gap example, the unadjusted gender pay (- \\$481) gap gives the right answer.\n\n::: {.fragment .fade-in}\n- But what about this example?\n\n|  | Healthy Lifestyle | Unhealthy Lifestyle |\n|:------|:------:|:------:|:------:|\n| Non-management: |  $3,163.30 (87)  |    $3,015.18 (59)   |\n| Management: |  $5,592.44 (13) |   $5,319.82 (41)   |\n:::\n\n\n## Simpson's Paradox (2)\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01_intro_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n-   Here, we would correctly infer that people with a healthy lifestyle earn more on average ($181.74). \n\n\n## Simpson's Paradox (3)\n\n-   What is the difference between the two examples?\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nlibrary(ggdag)\n\ncoord_dag <- list(\n  x = c(Gender = 0, Management = 1, Salary = 2),\n  y = c(Gender = 0, Management = 1, Salary = 0)\n)\n\ndag <- ggdag::dagify(Management ~ Gender,\n                     Salary ~ Gender,\n                     Salary ~ Management,\n                     coords = coord_dag)\n\ndag %>%\n  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +\n  geom_dag_point(colour = \"grey\") +\n  geom_dag_edges() +\n  geom_dag_text(colour = \"black\", size = 5) +\n  theme_dag(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](01_intro_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n- Management as \"mediator\"\n  \n:::\n\n::: {.column width=\"50%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nlibrary(ggdag)\n\ncoord_dag <- list(\n  x = c(Lifestyle = 0, Management = 1, Salary = 2),\n  y = c(Lifestyle = 0, Management = 1, Salary = 0)\n)\n\ndag <- ggdag::dagify(Lifestyle ~ Management,\n                     Salary ~ Lifestyle,\n                     Salary ~ Management,\n                     coords = coord_dag)\n\ndag %>%\n  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +\n  geom_dag_point(colour = \"grey\") +\n  geom_dag_edges() +\n  geom_dag_text(colour = \"black\", size = 5) +\n  theme_dag(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](01_intro_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n- Management as \"confounder\"\n\n:::\n\n::::\n\n\n\n## Simpson's Paradox (4)\n\n- Statistics alone doesn't help us to answer this question.\n- Note that the joint distribution of salaries is the same in both cases.\n- Both problems are thus identical from a statistical point of view.\n- Instead, we need to make causal assumptions in order to come to a conclusion here:\n  - Gender affects both a person's salary level and job position.\n  - Whereas lifestyle affects salaries, but is itself affected by a person's job position.\n- After the course you will know how to incorporate this kind of causal knowledge in your analysis in order to solve all sorts of  practical problems of causal inference.\n\n\n\n## Simpson's Paradox (5)\n\n\n![](_images/1/simpson_in_hr.png){.r-stretch fig-align=\"center\"}\n\n\n::: {.source}\nSource: [https://rpubs.com/lakenp/simpsonsparadox](https://rpubs.com/lakenp/simpsonsparadox).\n:::\n\n\n\n# Potential Outcomes {data-stack-name=\"Potential Outcomes\"}\n\n## Experimentalists’ View of Causal Inference {.smaller}\n\n- *\"No causation without manipulation.\"* `(Rubin, 1975; Holland, 1986)` \n- (Thought) Experiments with *manipulation*; also called *intervention* or *treatment*.\n- Treatments can be binary, continuous, or multi-valued.\n- Examples:\n  - take a drug vs. don't take a drug\n  - participate in a training program A vs B vs. don't participate\n  - amount of money spent on advertising\n  - change race of job applicants? Resumes with African-American- or White-sounding names `(Bertrand and Mullainathan, 2004)`. \n  - level of neuroticism?\n- The ***potential outcomes framework*** `(Neyman, 1923; Rubin, 1974)` is a way to formalize this idea.\n\n\n## Formal Notation of Potential Outcomes\n- $n$ experimental units indexed by $i = 1, . . . , n$\n- $Y$ is the outcome of interest.\n- $T_i$ is the (random) treatment variable for unit $i$. \n  - Assume it can take two levels: $t_i = 1$ for treatment and $t_i = 0$ for control.\n- $Y_i(1)$ is the *potential* outcome for unit $i$ if unit $i$ receives treatment.\n- $Y_i(0)$ is the *potential* outcome for unit $i$ if unit $i$ does not receive treatment.\n<br><br>\n- The ***Individual Treatment Effect (ITE)*** for unit $i$ is defined as:\n  - $\\tau_i = Y_i(1) - Y_i(0) \\quad \\forall \\quad i = 1, . . . , n$.\n\n\n  \n\n\n\n## Assumptions in the PO Framework (1) {.smaller}\n\nFor the potential outcomes and the *ITE* to be precisely defined, we need to make an initial set of assumptions:\n\n\n\n\n\n::: {.callout-note icon=false}\n\n## Assumption 1: \"No Interference\"\n\nUnit i’s potential outcomes do not depend on other units’ treatments.\n\n$Y_i(t_1,...,t_{i-1},t_i,t_{i+1},...t_n) = Y_i(t_i)$\n\n:::\n\n\n::: {.callout-note icon=false}\n\n## Assumption 2: \"Consistency.\"\n\nThere are no other versions of the treatment. Equivalently, we require that the treatment levels be well-defined, or have no ambiguity at least for the outcome of interest. If the treatment is $T$, then the observed outcome $Y$ is the potential outcome under treatment $T$. \n\nFormally, $T = t  => Y = Y(t)$ or equivalently $Y = Y(T)$\n\n:::\n\n\n::: {.callout-note icon=false}\n\n## Assumption 3: \"Stable Unit Treatment Value Assumption (SUTVA).\"\n\nBoth Assumptions 1 and 2 hold: $Y_i = Y(T_i)$\n\n:::\n\n\n## Fundamental Problem of Causal Inference\n\n- Typically, only one of those outcomes is *actually* observed for unit $i$:\n  - $Y_i = T_iY_i(1) + (1 − T_i)Y_i(0)$.\n- The other one remains unobserved or *counterfactual*.\n- This makes calculating the *ITE* $\\tau_i$ impossible.\n\n| $i$ | $T_i$ | $Y_i$ | $Y_i(1)$ | $Y_i(0)$ | $Y_i(1) - Y_i(0)$ |\n|---|---|---|:----:|:----:|:-----------:|\n| 1 | 0 | 0 | ?    | 0    | ?           |\n| 2 | 1 | 1 | 1    | ?    | ?           |\n| 3 | 1 | 0 | 0    | ?    | ?           |\n| 4 | 0 | 0 | ?    | 0    | ?           |\n| 5 | 0 | 1 | ?    | 1    | ?           |\n| 6 | 1 | 1 | 1    | ?    | ?           |\n\n\n## Getting Around the Fundamental Problem\n\n- Does the ***Average Treatment Effect (ATE)*** help? \n- Defined in terms of expectations:\n  - $\\tau = \\mathbb{E}[\\tau_i] = \\mathbb{E}[Y_i(1) - Y_i(0)] = \\mathbb{E}[Y_i(1)] - \\mathbb{E}[Y_i(0)]$ \n- Defined in terms of averages:\n  - $\\tau = \\frac{1}{n} \\sum_{i=1}^{n} [\\tau_i] = \\frac{1}{n} \\sum_{i=1}^{n} [Y_i(1) - Y_i(0)] = \\frac{1}{n} \\sum_{i=1}^{n} [Y_i(1)] - \\frac{1}{n} \\sum_{i=1}^{n} [Y_i(0)]$ \n\n<br><br>\n\n- Still not computable, because we don't know the counterfactuals.\n\n\n  \n\n\n## Assumptions in the PO Framework (2) \n\n- We need to make further assumptions to make progress.\n\n::: {.callout-note icon=false}\n\n## Assumption 4: \"Ignorability / Exchangeability\".\n\nIgnorability (of how people selected their treatment) is equivalent to random assignment into treatments.\n\nExchangeability means that observations in treatment and control group could be swapped, and one would still obtain the same outcomes. This implies that observations in groups are the same in all relevant aspects other than the treatment. \n\nFormally, $(Y(1), Y(0)) \\perp\\!\\!\\!\\perp T$.\n\n:::\n\n![](_images/1/dag_ass4.png){.r-stretch fig-align=\"center\"}\n\n\n## ATE Identification - Intuition {.smaller}\n\n- Using assumptions 4 and 2, we obtain the following simplification:\n  - $\\mathbb{E}[Y_i(1)] - \\mathbb{E}[Y_i(0)] = \\mathbb{E}[Y_i(1)|T_i=1] - \\mathbb{E}[Y_i(0)|T_i=0] = \\mathbb{E}[Y_i|T_i=1] - \\mathbb{E}[Y_i|T_i=0]$\n- This implies the *ATE* to be obtainable as *associational difference*:\n\n| $i$ | $T_i$ | $Y_i$ | $Y_i(1)$ | $Y_i(0)$ |\n|---|---|---|:----:|:----:|\n| 1 | 0 | 0 | ?    | 0    | \n| 4 | 0 | 0 | ?    | 0    |\n| 5 | 0 | 1 | ?    | 1    | \n| 2 | 1 | 1 | 1    | ?    | \n| 3 | 1 | 0 | 0    | ?    | \n| 6 | 1 | 1 | 1    | ?    |\n\n- We can then estimate $\\mathbb{E}[Y_i|T_i=1] = 0.66$ and $\\mathbb{E}[Y_i|T_i=0] = 0.33$ and use these values to replace the missing counterfactuals.\n- *ATE* is now ***identifiable*** in the sense that it can be computed from a purely statistical quantity.\n\n![](_images/1/flowchart.png){fig-align=\"center\" height=100}\n\n\n## Assumptions in the PO Framework (3) \n\n- Let's make exchangeability more realistic, i.e. *conditional* on covariates, so that subgroups will be exchangable.\n\n::: {.callout-note icon=false}\n\n## Assumption 5: \"Conditional Exchangeability / Unconfoundedness\".\n\nFormally, $(Y(1), Y(0)) \\perp\\!\\!\\!\\perp T \\, | \\, X$.\n\n:::\n\n![](_images/1/dag_ass5.png){.r-stretch fig-align=\"center\"}\n\n\n## Assumptions in the PO Framework (4) \n\n- Conditioning on many covariates can also be detrimental, because we might end up conditioning on a zero probability event for some subgroups / values of X (division by zero) \n\n::: {.callout-note icon=false}\n\n## Assumption 6: \"Positivity / Overlap / Common Support\".\n\nFor all values of covariates $x$ present in the population of interest (i.e. $x$ such that $P(X=x) > 0$), we have \n$0 < P(T=1|X=x) < 1$.\n\n:::\n\n- There is a trade-off between positivity and unconfoundedness.\n- Some models might be forced to *extrapolate* to regions without sufficient support by using their parametric assumptions.\n\n\n\n## Derivation of the Average Treatment Effect (ATE)\n\n- With the assumptions of conditional unconfoundedness, positivity, consistency, and no interference, we can identify the ATE as:\n\n::: {.callout-note icon=false}\n\n## Theorem 1: \"Identification of the ATE\":\n\n$\\tau = \\mathbb{E}[Y_i(1)] - \\mathbb{E}[Y_i(0)] = \\mathbb{E_X}[\\mathbb{E}[Y_i|T_i=1, X_i] - \\mathbb{E}[Y_i|T_i=0, X_i]]$\n\n:::\n\n\n## Derivation of the Average Treatment Effect (ATE)\n\n\n- Proof:\n\n\\begin{align*}\n\\tau = \\mathbb{E}[\\tau_i] &= \\mathbb{E}[Y_i(1) - Y_i(0)] \\\\\n&= \\mathbb{E}[Y_i(1)] - \\mathbb{E}[Y_i(0)] \\\\\n& \\text{(linearity of expectation)} \\\\\n&= \\mathbb{E}_X [\\mathbb{E}[Y_i(1) \\mid X_i]] - \\mathbb{E}_X [\\mathbb{E}[Y_i(0) \\mid X_i]] \\\\\n&\\text{(law of iterated expectations)} \\\\\n&= \\mathbb{E}_X [\\mathbb{E}[Y_i(1) \\mid T_i = 1, X_i]] - \\mathbb{E}_X [\\mathbb{E}[Y_i(0) \\mid T_i = 0, X_i]] \\\\\n&\\text{(unconfoundedness and positivity)} \\\\\n&= \\mathbb{E}_X [\\mathbb{E}[Y_i \\mid T_i = 1, X_i]] - \\mathbb{E}_X [\\mathbb{E}[Y_i \\mid T_i = 0, X_i]] \\\\\n&\\text{(consistency)}\n\\end{align*}\n\n\n## Other Causal Quantities\n\n- The ATE is just one of many causal quantities that can be estimated using the PO framework.\n\n::: {.callout-note icon=false}\n\n## \"Average Treatment Effect on the Treated\" (ATT):\n\n$ATT = \\mathbb{E}[Y_i(1)|T_i=1] - \\mathbb{E}[Y_i(0)|T_i=1]$\n\n:::\n\n::: {.callout-note icon=false}\n\n## \"Conditional Average Treatment Effect\" (CATE):\n\n$CATE = \\mathbb{E}[Y_i(1)|X_i=x] - \\mathbb{E}[Y_i(0)|X_i=x]$\n\n:::\n\n\n# {.center .center-x data-state=\"hide-menubar\"}\n<style>\n.table-text {\n  text-align: center !important;\n  font-size: 2em;\n  padding-bottom: 1em !important;\n}\n.row-bottom {\n  text-align: center !important;\n  padding-top: 2em !important;\n}\n</style>\n<table width = \"100%\">\n<tbody>\n  <tr>\n    <td colspan=\"2\" class=\"table-text\">Thank you for your attention!</td>\n  </tr>\n  <tr >\n    <td class=\"row-bottom\" style=\"vertical-align: baseline; width: 50%;\">\n          <img src=\"https://raw.githubusercontent.com/christophihl/TIE_website/main/assets/images/logo.svg\" style=\"vertical-align: middle; width: 60%; height: auto;\" />\n          <img src=\"author_pic.jpg\" class=\"picture\" style=\"vertical-align: middle; horizontal-align: right; width: 30%; height: auto;\" />\n    </td>\n    <td class = \"row-bottom\" style = \"vertical-align: middle; width = 50%\">\n      <ul style = \"list-style:none;\">\n        <li><a href = \"https://www.startupengineer.io/authors/ihl/\" target = \"_blank\"><i class = \"fas fa-home\"></i> startupengineer.io/authors/ihl</a></li>\n        <li><a href = \"https://www.linkedin.com/in/christoph-ihl/\" target = \"_blank\"><i class = \"fab fa-linkedin\"></i> christoph-ihl</a></li>\n        <li><a href = \"https://github.com/christophihl\" target = \"_blank\"><i class = \"fab fa-github\"></i> christophihl</a></li>\n        <li><a href = \"https://twitter.com/Ihluminate/\" target = \"_blank\"><i class = \"fab fa-twitter\"></i> Ihluminate</a></li>\n      </ul>\n    </td>\n  </tr>\n</tbody>\n</table>\n\n",
    "supporting": [
      "01_intro_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}